version: '3'
services:
  # デプロイツール
  firebase:
    build: ./firebase
    env_file: .env
    volumes:
      - ../config/firebase.json:/app/firebase.json
      - ../config/firestore.rules:/app/firestore.rules
      - ../config/storage.rules:/app/storage.rules
    ports:
      - 9005:9005
  gcloud:
    build: ./gcloud
    volumes:
      - ../config/cors.json:/app/cors.json
